rootUser: admin
rootPassword: Minio@123

mode: standalone

replicas: 1
persistence:
  enabled: true
  storageClass: longhorn
  size: 3Gi

service:
  type: LoadBalancer

resources:
  requests:
    memory: 512Mi
    cpu: 250m
